---
# tasks file for klousiaj.wso2-das

#### section for creating wso2 user and appropriate credentials and access. ####

- name: Create service account for wso2
  become: yes
  become_method: sudo
  user: 
    name: "{{ wso2_user }}"
    system: yes
    home: "/home/{{ wso2_user }}"
    shell: /bin/false
    state: present
    
- name: Add the wso2-app-sudoers script 
  become: yes
  become_method: sudo
  template:
    src: wso2-app-sudoers.j2
    dest: "/etc/sudoers.d/{{wso2_app}}-sudoers"
    validate: 'visudo -cf %s'
    mode: 0440
  
- include: centos-main.yml
  when: ansible_os_family == 'RedHat'

- name: Check if the version already exists on the remote system.
  stat: 
    path: "{{ carbon_base }}/{{ wso2_app_directory }}"
  register: version_deployed

- name: Copy the file and unzip it on the remote system
  become: yes
#  become_method: sudo
#  become_user: "{{ wso2_user }}"
  remote_user: itspp
  unarchive:
    src: "{{ item }}"
    dest: "/home/{{ wso2_user }}/"
    mode: 0755
  with_items:
    - "{{ wso2_app_archive }}"
  when: not version_deployed.stat.exists
    
- name: Make the base directory for the wso2 apps.
  become: yes
  become_method: sudo
  file: 
    dest: "{{ carbon_base }}"
    owner: "{{ wso2_user }}"
    group: "{{ wso2_user }}"
    mode: 0755
    state: directory
  when: not version_deployed.stat.exists

- name: Move WSO2 directory into place.
  become: yes
  become_method: sudo
  command: "mv /home/{{ wso2_user }}/{{ wso2_app_directory }} {{ carbon_base }}/{{ wso2_app_directory }}"
  when: not version_deployed.stat.exists
  
- name: Create link to the install directory at carbon_home.
  become: yes
#  remote_user: "{{ wso2_user }}"
  file: 
    state: link
    src: "{{ carbon_base }}/{{ wso2_app_directory }}"
    dest: "{{ carbon_home }}"
  when: not version_deployed.stat.exists
  
- name: Add wso2 symlink to /usr/local/bin.
  become: yes
#  become_method: sudo
  file:
    src: "{{ carbon_home }}/bin/wso2server.sh"
    dest: "/usr/local/bin/{{ wso2_app }}"
    state: link
  when: not version_deployed.stat.exists

#### section for initializing the application to start and run as a service. ####
- name: Add wso2 app init script.
  become: yes
#  become_method: sudo
  template:
    src: wso2-app-init_d.j2
    dest: "/etc/init.d/{{ wso2_app }}"
    mode: 0755
  notify: restart wso2-app

- name: Ensure wso2-app is set to start on boot.
  become: yes
#  become_method: sudo
  service: 
    name: "{{ wso2_app }}" 
    enabled: yes
    state: started
  notify: restart wso2-app
